### ISSUE TITLE
Datatype in costum logic

### ISSUE THREAD

**Issue by GitHubber1** [marcelotto/spread2rdf#7]
Hello Marcel,

thanks for adding the feature to define the rdf:datatype, that is really helpful. Is it also possible to set the rdf:datatype using statement methods in costum logic blocks?

Thanks a lot,
Andy

**Comment by marcelotto** [comment]
Yes, this should be possible already. The arguments are only used to construct `RDF::Statements`, so you can provide the object as a `RDF::Literal`:

``` ruby
statement(subject, predicate, RDF::Literal('2014-02-27', datatype: RDF::XSD.date))
```

**Comment by GitHubber1** [comment]
Thank you for your help, I did not know that.
